function bar(e){try{foo()}catch(t){alert("Exception caught (foo not defined)")}alert(e)}bar(10)